#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 183
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 1
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 47

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_import = 2,
  anon_sym_DOT = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_as = 7,
  anon_sym_if = 8,
  anon_sym_and = 9,
  anon_sym_fn = 10,
  anon_sym_extern = 11,
  anon_sym_COLON = 12,
  anon_sym_DOT_DOT_DOT = 13,
  anon_sym_DASH_GT = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_PLUS = 17,
  anon_sym_mut = 18,
  sym_public = 19,
  anon_sym_ref = 20,
  anon_sym_uni = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  sym_self = 24,
  sym_comment = 25,
  sym_constant = 26,
  sym_source_file = 27,
  sym__top_level = 28,
  sym_import = 29,
  sym_path = 30,
  sym_symbols = 31,
  sym__symbol = 32,
  sym_import_as = 33,
  sym_tags = 34,
  sym_external_function = 35,
  sym_extern_arguments = 36,
  sym_module_method = 37,
  sym_method_arguments = 38,
  sym_argument = 39,
  sym_rest_argument = 40,
  sym__returns = 41,
  sym_type_parameters = 42,
  sym_type_parameter = 43,
  sym_type_parameter_requirements = 44,
  sym__type_parameter_requirement = 45,
  sym_mutable_requirement = 46,
  sym__type = 47,
  sym_generic_type = 48,
  sym_type_arguments = 49,
  sym_ref_type = 50,
  sym_mut_type = 51,
  sym_uni_type = 52,
  sym_fn_type = 53,
  sym_fn_type_arguments = 54,
  sym_block = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_path_repeat1 = 57,
  aux_sym_symbols_repeat1 = 58,
  aux_sym_tags_repeat1 = 59,
  aux_sym_extern_arguments_repeat1 = 60,
  aux_sym_type_parameters_repeat1 = 61,
  aux_sym_type_parameter_requirements_repeat1 = 62,
  aux_sym_type_arguments_repeat1 = 63,
  alias_sym_type = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_import] = "import",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_as] = "as",
  [anon_sym_if] = "if",
  [anon_sym_and] = "and",
  [anon_sym_fn] = "fn",
  [anon_sym_extern] = "extern",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_mut] = "mut",
  [sym_public] = "public",
  [anon_sym_ref] = "ref",
  [anon_sym_uni] = "uni",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_self] = "self",
  [sym_comment] = "comment",
  [sym_constant] = "constant",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym_import] = "import",
  [sym_path] = "path",
  [sym_symbols] = "symbols",
  [sym__symbol] = "_symbol",
  [sym_import_as] = "import_as",
  [sym_tags] = "tags",
  [sym_external_function] = "external_function",
  [sym_extern_arguments] = "arguments",
  [sym_module_method] = "module_method",
  [sym_method_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_rest_argument] = "rest_argument",
  [sym__returns] = "_returns",
  [sym_type_parameters] = "type_parameters",
  [sym_type_parameter] = "type_parameter",
  [sym_type_parameter_requirements] = "requirements",
  [sym__type_parameter_requirement] = "_type_parameter_requirement",
  [sym_mutable_requirement] = "mut",
  [sym__type] = "_type",
  [sym_generic_type] = "generic_type",
  [sym_type_arguments] = "type_arguments",
  [sym_ref_type] = "ref_type",
  [sym_mut_type] = "mut_type",
  [sym_uni_type] = "uni_type",
  [sym_fn_type] = "fn_type",
  [sym_fn_type_arguments] = "arguments",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_symbols_repeat1] = "symbols_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_extern_arguments_repeat1] = "extern_arguments_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_type_parameter_requirements_repeat1] = "type_parameter_requirements_repeat1",
  [aux_sym_type_arguments_repeat1] = "type_arguments_repeat1",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_mut] = anon_sym_mut,
  [sym_public] = sym_public,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_uni] = anon_sym_uni,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_self] = sym_self,
  [sym_comment] = sym_comment,
  [sym_constant] = sym_constant,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym_import] = sym_import,
  [sym_path] = sym_path,
  [sym_symbols] = sym_symbols,
  [sym__symbol] = sym__symbol,
  [sym_import_as] = sym_import_as,
  [sym_tags] = sym_tags,
  [sym_external_function] = sym_external_function,
  [sym_extern_arguments] = sym_extern_arguments,
  [sym_module_method] = sym_module_method,
  [sym_method_arguments] = sym_extern_arguments,
  [sym_argument] = sym_argument,
  [sym_rest_argument] = sym_rest_argument,
  [sym__returns] = sym__returns,
  [sym_type_parameters] = sym_type_parameters,
  [sym_type_parameter] = sym_type_parameter,
  [sym_type_parameter_requirements] = sym_type_parameter_requirements,
  [sym__type_parameter_requirement] = sym__type_parameter_requirement,
  [sym_mutable_requirement] = sym_mutable_requirement,
  [sym__type] = sym__type,
  [sym_generic_type] = sym_generic_type,
  [sym_type_arguments] = sym_type_arguments,
  [sym_ref_type] = sym_ref_type,
  [sym_mut_type] = sym_mut_type,
  [sym_uni_type] = sym_uni_type,
  [sym_fn_type] = sym_fn_type,
  [sym_fn_type_arguments] = sym_extern_arguments,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_symbols_repeat1] = aux_sym_symbols_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_extern_arguments_repeat1] = aux_sym_extern_arguments_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_type_parameter_requirements_repeat1] = aux_sym_type_parameter_requirements_repeat1,
  [aux_sym_type_arguments_repeat1] = aux_sym_type_arguments_repeat1,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [sym_public] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uni] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [sym__symbol] = {
    .visible = false,
    .named = true,
  },
  [sym_import_as] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_external_function] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_module_method] = {
    .visible = true,
    .named = true,
  },
  [sym_method_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_rest_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__returns] = {
    .visible = false,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter_requirements] = {
    .visible = true,
    .named = true,
  },
  [sym__type_parameter_requirement] = {
    .visible = false,
    .named = true,
  },
  [sym_mutable_requirement] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_type] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_type] = {
    .visible = true,
    .named = true,
  },
  [sym_uni_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbols_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extern_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameter_requirements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_arguments = 2,
  field_body = 3,
  field_name = 4,
  field_path = 5,
  field_requirements = 6,
  field_returns = 7,
  field_symbols = 8,
  field_tags = 9,
  field_type = 10,
  field_type_parameters = 11,
  field_visibility = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_name] = "name",
  [field_path] = "path",
  [field_requirements] = "requirements",
  [field_returns] = "returns",
  [field_symbols] = "symbols",
  [field_tags] = "tags",
  [field_type] = "type",
  [field_type_parameters] = "type_parameters",
  [field_visibility] = "visibility",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 3},
  [13] = {.index = 22, .length = 1},
  [14] = {.index = 23, .length = 3},
  [15] = {.index = 26, .length = 3},
  [16] = {.index = 29, .length = 3},
  [17] = {.index = 32, .length = 3},
  [18] = {.index = 35, .length = 3},
  [19] = {.index = 38, .length = 3},
  [20] = {.index = 41, .length = 3},
  [21] = {.index = 44, .length = 3},
  [22] = {.index = 47, .length = 3},
  [23] = {.index = 50, .length = 4},
  [24] = {.index = 54, .length = 4},
  [25] = {.index = 58, .length = 4},
  [26] = {.index = 62, .length = 1},
  [27] = {.index = 63, .length = 1},
  [28] = {.index = 64, .length = 1},
  [29] = {.index = 65, .length = 2},
  [30] = {.index = 67, .length = 2},
  [31] = {.index = 69, .length = 4},
  [32] = {.index = 73, .length = 4},
  [33] = {.index = 77, .length = 4},
  [34] = {.index = 81, .length = 3},
  [35] = {.index = 84, .length = 4},
  [36] = {.index = 88, .length = 4},
  [37] = {.index = 92, .length = 4},
  [38] = {.index = 96, .length = 4},
  [39] = {.index = 100, .length = 5},
  [40] = {.index = 105, .length = 5},
  [41] = {.index = 110, .length = 5},
  [42] = {.index = 115, .length = 2},
  [43] = {.index = 117, .length = 2},
  [44] = {.index = 119, .length = 5},
  [45] = {.index = 124, .length = 5},
  [46] = {.index = 129, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_path, 1},
    {field_symbols, 2},
  [3] =
    {field_path, 1},
    {field_tags, 2},
  [5] =
    {field_name, 2},
  [6] =
    {field_body, 2},
    {field_name, 1},
  [8] =
    {field_path, 1},
    {field_symbols, 2},
    {field_tags, 3},
  [11] =
    {field_arguments, 3},
    {field_name, 2},
  [13] =
    {field_name, 2},
    {field_returns, 3},
  [15] =
    {field_body, 3},
    {field_name, 2},
  [17] =
    {field_name, 3},
    {field_visibility, 1},
  [19] =
    {field_body, 3},
    {field_name, 2},
    {field_visibility, 1},
  [22] =
    {field_name, 0},
  [23] =
    {field_arguments, 2},
    {field_body, 3},
    {field_name, 1},
  [26] =
    {field_body, 3},
    {field_name, 1},
    {field_returns, 2},
  [29] =
    {field_body, 3},
    {field_name, 1},
    {field_type_parameters, 2},
  [32] =
    {field_arguments, 3},
    {field_name, 2},
    {field_returns, 4},
  [35] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 2},
  [38] =
    {field_body, 4},
    {field_name, 2},
    {field_returns, 3},
  [41] =
    {field_arguments, 4},
    {field_name, 3},
    {field_visibility, 1},
  [44] =
    {field_name, 3},
    {field_returns, 4},
    {field_visibility, 1},
  [47] =
    {field_body, 4},
    {field_name, 3},
    {field_visibility, 1},
  [50] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 2},
    {field_visibility, 1},
  [54] =
    {field_body, 4},
    {field_name, 2},
    {field_returns, 3},
    {field_visibility, 1},
  [58] =
    {field_body, 4},
    {field_name, 2},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [62] =
    {field_returns, 1},
  [63] =
    {field_arguments, 1},
  [64] =
    {field_type, 1},
  [65] =
    {field_arguments, 1},
    {field_name, 0},
  [67] =
    {field_name, 0},
    {field_requirements, 1},
  [69] =
    {field_arguments, 2},
    {field_body, 4},
    {field_name, 1},
    {field_returns, 3},
  [73] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 1},
    {field_type_parameters, 2},
  [77] =
    {field_body, 4},
    {field_name, 1},
    {field_returns, 3},
    {field_type_parameters, 2},
  [81] =
    {field_alias, 1},
    {field_alias, 2},
    {field_name, 0},
  [84] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
  [88] =
    {field_arguments, 4},
    {field_name, 3},
    {field_returns, 5},
    {field_visibility, 1},
  [92] =
    {field_arguments, 4},
    {field_body, 5},
    {field_name, 3},
    {field_visibility, 1},
  [96] =
    {field_body, 5},
    {field_name, 3},
    {field_returns, 4},
    {field_visibility, 1},
  [100] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
    {field_visibility, 1},
  [105] =
    {field_arguments, 4},
    {field_body, 5},
    {field_name, 2},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [110] =
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [115] =
    {field_name, 0},
    {field_type, 2},
  [117] =
    {field_arguments, 1},
    {field_returns, 2},
  [119] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 1},
    {field_returns, 4},
    {field_type_parameters, 2},
  [124] =
    {field_arguments, 4},
    {field_body, 6},
    {field_name, 3},
    {field_returns, 5},
    {field_visibility, 1},
  [129] =
    {field_arguments, 4},
    {field_body, 6},
    {field_name, 2},
    {field_returns, 5},
    {field_type_parameters, 3},
    {field_visibility, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [12] = {
    [0] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(10);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '.') ADVANCE(2);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_constant);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_public);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_uni);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_self);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [sym_public] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_uni] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_self] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_constant] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(181),
    [sym__top_level] = STATE(21),
    [sym_import] = STATE(21),
    [sym_external_function] = STATE(21),
    [sym_module_method] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(134), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [30] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(108), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [60] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(108), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [90] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    STATE(108), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [120] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(137), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [150] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(108), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [180] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(41), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [207] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(153), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [234] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(108), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [261] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(39), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [288] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(34), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [315] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_mut,
    ACTIONS(17), 1,
      anon_sym_ref,
    ACTIONS(19), 1,
      anon_sym_uni,
    ACTIONS(21), 1,
      sym_constant,
    STATE(38), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [342] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    STATE(17), 1,
      sym_fn_type_arguments,
    STATE(40), 1,
      sym__returns,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_type_arguments,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [386] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_extern_arguments,
    STATE(56), 1,
      sym__returns,
    STATE(96), 1,
      sym_block,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    STATE(37), 1,
      sym__returns,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [432] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_extern_arguments,
    STATE(60), 1,
      sym__returns,
    STATE(125), 1,
      sym_block,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [487] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(26), 5,
      sym__top_level,
      sym_import,
      sym_external_function,
      sym_module_method,
      aux_sym_source_file_repeat1,
  [507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [521] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    STATE(50), 1,
      sym_type_parameters,
    STATE(79), 1,
      sym_method_arguments,
    STATE(86), 1,
      sym_block,
    STATE(156), 1,
      sym__returns,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [563] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    STATE(49), 1,
      sym_type_parameters,
    STATE(78), 1,
      sym_method_arguments,
    STATE(110), 1,
      sym_block,
    STATE(169), 1,
      sym__returns,
  [591] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_import,
    ACTIONS(72), 1,
      anon_sym_fn,
    STATE(26), 5,
      sym__top_level,
      sym_import,
      sym_external_function,
      sym_module_method,
      aux_sym_source_file_repeat1,
  [611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [681] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym_path_repeat1,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
  [698] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_mut,
    ACTIONS(93), 1,
      sym_constant,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(85), 3,
      sym__type_parameter_requirement,
      sym_mutable_requirement,
      sym_generic_type,
  [717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [730] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym_path_repeat1,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
  [747] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym__returns,
    STATE(98), 1,
      sym_block,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [768] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [794] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [833] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 1,
      anon_sym_if,
    STATE(55), 1,
      sym_symbols,
    STATE(92), 1,
      sym_tags,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [854] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(32), 1,
      aux_sym_path_repeat1,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
  [871] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym__returns,
    STATE(122), 1,
      sym_block,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [892] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(128), 1,
      sym_constant,
    ACTIONS(124), 2,
      sym_self,
      sym_identifier,
    STATE(166), 2,
      sym__symbol,
      sym_import_as,
  [910] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_constant,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    ACTIONS(124), 2,
      sym_self,
      sym_identifier,
    STATE(166), 2,
      sym__symbol,
      sym_import_as,
  [928] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_constant,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    ACTIONS(124), 2,
      sym_self,
      sym_identifier,
    STATE(117), 2,
      sym__symbol,
      sym_import_as,
  [946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
  [958] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_method_arguments,
    STATE(118), 1,
      sym_block,
    STATE(158), 1,
      sym__returns,
  [980] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_method_arguments,
    STATE(88), 1,
      sym_block,
    STATE(159), 1,
      sym__returns,
  [1002] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(138), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(147), 1,
      sym_argument,
    STATE(168), 1,
      sym_rest_argument,
  [1021] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_and,
    STATE(65), 1,
      aux_sym_tags_repeat1,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1036] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_constant,
    ACTIONS(124), 2,
      sym_self,
      sym_identifier,
    STATE(166), 2,
      sym__symbol,
      sym_import_as,
  [1051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1062] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_if,
    STATE(87), 1,
      sym_tags,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1077] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(123), 1,
      sym_block,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1092] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_type_arguments,
    ACTIONS(150), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1129] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(97), 1,
      sym_block,
    ACTIONS(156), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1144] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(129), 1,
      sym_block,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1159] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(120), 1,
      sym_block,
    ACTIONS(160), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1174] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(147), 1,
      sym_argument,
    STATE(150), 1,
      sym_rest_argument,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1204] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_and,
    STATE(65), 1,
      aux_sym_tags_repeat1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_mut,
    ACTIONS(93), 1,
      sym_constant,
    STATE(95), 3,
      sym__type_parameter_requirement,
      sym_mutable_requirement,
      sym_generic_type,
  [1245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_and,
    STATE(52), 1,
      aux_sym_tags_repeat1,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
  [1281] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
  [1291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
  [1301] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      sym_argument,
  [1317] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_and,
      anon_sym_fn,
  [1337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_PLUS,
    STATE(83), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1351] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(106), 1,
      sym_block,
    STATE(145), 1,
      sym__returns,
  [1367] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(135), 1,
      sym_block,
    STATE(163), 1,
      sym__returns,
  [1383] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(94), 1,
      sym_block,
    STATE(164), 1,
      sym__returns,
  [1399] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_type_arguments_repeat1,
    ACTIONS(196), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COLON,
    STATE(146), 1,
      sym_type_parameter_requirements,
    ACTIONS(198), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1427] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(206), 2,
      anon_sym_import,
      anon_sym_fn,
  [1441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_PLUS,
    STATE(83), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1455] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(126), 1,
      sym_block,
    STATE(157), 1,
      sym__returns,
  [1471] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_PLUS,
    STATE(76), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1512] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(147), 1,
      sym_argument,
  [1525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_extern,
    ACTIONS(227), 1,
      sym_public,
  [1538] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(132), 1,
      aux_sym_extern_arguments_repeat1,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1560] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1614] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(119), 1,
      aux_sym_extern_arguments_repeat1,
  [1627] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(130), 1,
      sym_argument,
  [1640] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      sym_constant,
    STATE(167), 1,
      sym_type_parameter,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1662] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    STATE(144), 1,
      aux_sym_type_parameters_repeat1,
  [1675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1684] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_constant,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    STATE(140), 1,
      sym_type_parameter,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1724] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(160), 1,
      sym_rest_argument,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      aux_sym_symbols_repeat1,
  [1768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(112), 1,
      aux_sym_symbols_repeat1,
  [1781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_as,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_as,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_type_arguments_repeat1,
  [1816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(113), 1,
      aux_sym_symbols_repeat1,
  [1829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    STATE(132), 1,
      aux_sym_extern_arguments_repeat1,
  [1851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1860] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_type_arguments_repeat1,
  [1873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1891] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1945] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_extern_arguments_repeat1,
  [1958] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    STATE(147), 1,
      sym_argument,
  [1971] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_RPAREN,
    STATE(132), 1,
      aux_sym_extern_arguments_repeat1,
  [1984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [1993] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      aux_sym_type_arguments_repeat1,
  [2006] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [2015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2024] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    STATE(116), 1,
      aux_sym_type_arguments_repeat1,
  [2037] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [2046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [2055] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    STATE(103), 1,
      aux_sym_type_parameters_repeat1,
  [2068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 3,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
  [2086] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_constant,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
    STATE(167), 1,
      sym_type_parameter,
  [2099] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    ACTIONS(354), 1,
      anon_sym_RBRACK,
    STATE(144), 1,
      aux_sym_type_parameters_repeat1,
  [2112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(142), 1,
      sym_block,
  [2122] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      sym_identifier,
    ACTIONS(362), 1,
      anon_sym_extern,
  [2156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(364), 1,
      anon_sym_COMMA,
  [2166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_constant,
    STATE(167), 1,
      sym_type_parameter,
  [2200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    STATE(147), 1,
      sym_argument,
  [2210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(93), 1,
      sym_block,
  [2220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(128), 1,
      sym_block,
  [2230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(107), 1,
      sym_block,
  [2240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(127), 1,
      sym_block,
  [2250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(372), 1,
      anon_sym_COMMA,
  [2260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      sym_identifier,
    STATE(42), 1,
      sym_path,
  [2278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_block,
  [2288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(124), 1,
      sym_block,
  [2298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_COMMA,
    ACTIONS(382), 1,
      anon_sym_RPAREN,
  [2332] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(133), 1,
      sym_block,
  [2342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_RBRACE,
  [2357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      anon_sym_RPAREN,
  [2364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_constant,
  [2371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      sym_identifier,
  [2378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      sym_identifier,
  [2385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_identifier,
  [2392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      sym_identifier,
  [2399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      anon_sym_RPAREN,
  [2406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      anon_sym_COLON,
  [2413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_identifier,
  [2420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(402), 1,
      ts_builtin_sym_end,
  [2427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 207,
  [SMALL_STATE(10)] = 234,
  [SMALL_STATE(11)] = 261,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 315,
  [SMALL_STATE(14)] = 342,
  [SMALL_STATE(15)] = 367,
  [SMALL_STATE(16)] = 386,
  [SMALL_STATE(17)] = 413,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 459,
  [SMALL_STATE(20)] = 473,
  [SMALL_STATE(21)] = 487,
  [SMALL_STATE(22)] = 507,
  [SMALL_STATE(23)] = 521,
  [SMALL_STATE(24)] = 549,
  [SMALL_STATE(25)] = 563,
  [SMALL_STATE(26)] = 591,
  [SMALL_STATE(27)] = 611,
  [SMALL_STATE(28)] = 625,
  [SMALL_STATE(29)] = 639,
  [SMALL_STATE(30)] = 653,
  [SMALL_STATE(31)] = 667,
  [SMALL_STATE(32)] = 681,
  [SMALL_STATE(33)] = 698,
  [SMALL_STATE(34)] = 717,
  [SMALL_STATE(35)] = 730,
  [SMALL_STATE(36)] = 747,
  [SMALL_STATE(37)] = 768,
  [SMALL_STATE(38)] = 781,
  [SMALL_STATE(39)] = 794,
  [SMALL_STATE(40)] = 807,
  [SMALL_STATE(41)] = 820,
  [SMALL_STATE(42)] = 833,
  [SMALL_STATE(43)] = 854,
  [SMALL_STATE(44)] = 871,
  [SMALL_STATE(45)] = 892,
  [SMALL_STATE(46)] = 910,
  [SMALL_STATE(47)] = 928,
  [SMALL_STATE(48)] = 946,
  [SMALL_STATE(49)] = 958,
  [SMALL_STATE(50)] = 980,
  [SMALL_STATE(51)] = 1002,
  [SMALL_STATE(52)] = 1021,
  [SMALL_STATE(53)] = 1036,
  [SMALL_STATE(54)] = 1051,
  [SMALL_STATE(55)] = 1062,
  [SMALL_STATE(56)] = 1077,
  [SMALL_STATE(57)] = 1092,
  [SMALL_STATE(58)] = 1107,
  [SMALL_STATE(59)] = 1118,
  [SMALL_STATE(60)] = 1129,
  [SMALL_STATE(61)] = 1144,
  [SMALL_STATE(62)] = 1159,
  [SMALL_STATE(63)] = 1174,
  [SMALL_STATE(64)] = 1193,
  [SMALL_STATE(65)] = 1204,
  [SMALL_STATE(66)] = 1219,
  [SMALL_STATE(67)] = 1230,
  [SMALL_STATE(68)] = 1245,
  [SMALL_STATE(69)] = 1256,
  [SMALL_STATE(70)] = 1271,
  [SMALL_STATE(71)] = 1281,
  [SMALL_STATE(72)] = 1291,
  [SMALL_STATE(73)] = 1301,
  [SMALL_STATE(74)] = 1317,
  [SMALL_STATE(75)] = 1327,
  [SMALL_STATE(76)] = 1337,
  [SMALL_STATE(77)] = 1351,
  [SMALL_STATE(78)] = 1367,
  [SMALL_STATE(79)] = 1383,
  [SMALL_STATE(80)] = 1399,
  [SMALL_STATE(81)] = 1413,
  [SMALL_STATE(82)] = 1427,
  [SMALL_STATE(83)] = 1441,
  [SMALL_STATE(84)] = 1455,
  [SMALL_STATE(85)] = 1471,
  [SMALL_STATE(86)] = 1485,
  [SMALL_STATE(87)] = 1494,
  [SMALL_STATE(88)] = 1503,
  [SMALL_STATE(89)] = 1512,
  [SMALL_STATE(90)] = 1525,
  [SMALL_STATE(91)] = 1538,
  [SMALL_STATE(92)] = 1551,
  [SMALL_STATE(93)] = 1560,
  [SMALL_STATE(94)] = 1569,
  [SMALL_STATE(95)] = 1578,
  [SMALL_STATE(96)] = 1587,
  [SMALL_STATE(97)] = 1596,
  [SMALL_STATE(98)] = 1605,
  [SMALL_STATE(99)] = 1614,
  [SMALL_STATE(100)] = 1627,
  [SMALL_STATE(101)] = 1640,
  [SMALL_STATE(102)] = 1653,
  [SMALL_STATE(103)] = 1662,
  [SMALL_STATE(104)] = 1675,
  [SMALL_STATE(105)] = 1684,
  [SMALL_STATE(106)] = 1697,
  [SMALL_STATE(107)] = 1706,
  [SMALL_STATE(108)] = 1715,
  [SMALL_STATE(109)] = 1724,
  [SMALL_STATE(110)] = 1737,
  [SMALL_STATE(111)] = 1746,
  [SMALL_STATE(112)] = 1755,
  [SMALL_STATE(113)] = 1768,
  [SMALL_STATE(114)] = 1781,
  [SMALL_STATE(115)] = 1792,
  [SMALL_STATE(116)] = 1803,
  [SMALL_STATE(117)] = 1816,
  [SMALL_STATE(118)] = 1829,
  [SMALL_STATE(119)] = 1838,
  [SMALL_STATE(120)] = 1851,
  [SMALL_STATE(121)] = 1860,
  [SMALL_STATE(122)] = 1873,
  [SMALL_STATE(123)] = 1882,
  [SMALL_STATE(124)] = 1891,
  [SMALL_STATE(125)] = 1900,
  [SMALL_STATE(126)] = 1909,
  [SMALL_STATE(127)] = 1918,
  [SMALL_STATE(128)] = 1927,
  [SMALL_STATE(129)] = 1936,
  [SMALL_STATE(130)] = 1945,
  [SMALL_STATE(131)] = 1958,
  [SMALL_STATE(132)] = 1971,
  [SMALL_STATE(133)] = 1984,
  [SMALL_STATE(134)] = 1993,
  [SMALL_STATE(135)] = 2006,
  [SMALL_STATE(136)] = 2015,
  [SMALL_STATE(137)] = 2024,
  [SMALL_STATE(138)] = 2037,
  [SMALL_STATE(139)] = 2046,
  [SMALL_STATE(140)] = 2055,
  [SMALL_STATE(141)] = 2068,
  [SMALL_STATE(142)] = 2077,
  [SMALL_STATE(143)] = 2086,
  [SMALL_STATE(144)] = 2099,
  [SMALL_STATE(145)] = 2112,
  [SMALL_STATE(146)] = 2122,
  [SMALL_STATE(147)] = 2130,
  [SMALL_STATE(148)] = 2138,
  [SMALL_STATE(149)] = 2146,
  [SMALL_STATE(150)] = 2156,
  [SMALL_STATE(151)] = 2166,
  [SMALL_STATE(152)] = 2174,
  [SMALL_STATE(153)] = 2182,
  [SMALL_STATE(154)] = 2190,
  [SMALL_STATE(155)] = 2200,
  [SMALL_STATE(156)] = 2210,
  [SMALL_STATE(157)] = 2220,
  [SMALL_STATE(158)] = 2230,
  [SMALL_STATE(159)] = 2240,
  [SMALL_STATE(160)] = 2250,
  [SMALL_STATE(161)] = 2260,
  [SMALL_STATE(162)] = 2268,
  [SMALL_STATE(163)] = 2278,
  [SMALL_STATE(164)] = 2288,
  [SMALL_STATE(165)] = 2298,
  [SMALL_STATE(166)] = 2306,
  [SMALL_STATE(167)] = 2314,
  [SMALL_STATE(168)] = 2322,
  [SMALL_STATE(169)] = 2332,
  [SMALL_STATE(170)] = 2342,
  [SMALL_STATE(171)] = 2350,
  [SMALL_STATE(172)] = 2357,
  [SMALL_STATE(173)] = 2364,
  [SMALL_STATE(174)] = 2371,
  [SMALL_STATE(175)] = 2378,
  [SMALL_STATE(176)] = 2385,
  [SMALL_STATE(177)] = 2392,
  [SMALL_STATE(178)] = 2399,
  [SMALL_STATE(179)] = 2406,
  [SMALL_STATE(180)] = 2413,
  [SMALL_STATE(181)] = 2420,
  [SMALL_STATE(182)] = 2427,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, .production_id = 12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 10),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 2, .production_id = 27),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 3, .production_id = 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(162),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(90),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, .production_id = 29),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_type, 2, .production_id = 28),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2), SHIFT_REPEAT(177),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 3, .production_id = 43),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_type, 2, .production_id = 28),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uni_type, 2, .production_id = 28),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 2, .production_id = 26),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__returns, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, .production_id = 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 20),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 6),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3, .production_id = 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 21),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_parameter_requirement, 1, .production_id = 12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 8),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 36),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 17),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2), SHIFT_REPEAT(175),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 4),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 5),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2), SHIFT_REPEAT(10),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 1, .production_id = 13),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameter_requirements_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameter_requirements_repeat1, 2), SHIFT_REPEAT(67),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 11),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 6),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 25),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(180),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3, .production_id = 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 24),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 23),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 22),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 19),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 18),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 31),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 32),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 33),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 3, .production_id = 5),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 5),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_symbols_repeat1, 2), SHIFT_REPEAT(53),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_symbols_repeat1, 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol, 1),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 16),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 35),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 37),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 38),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 39),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 9),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 40),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 41),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 7, .production_id = 46),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 7, .production_id = 45),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [318] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extern_arguments_repeat1, 2), SHIFT_REPEAT(155),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extern_arguments_repeat1, 2),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 15),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 14),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 2),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mutable_requirement, 1),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 44),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [351] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2), SHIFT_REPEAT(154),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 2, .production_id = 30),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 3),
  [360] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [362] = {.entry = {.count = 1, .reusable = false}}, SHIFT(174),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 2),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 4),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 42),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest_argument, 1),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 5),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [384] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_as, 3, .production_id = 34),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [402] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_inko() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
