#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 188
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 1
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 47

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_import = 2,
  anon_sym_DOT = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_as = 7,
  anon_sym_if = 8,
  anon_sym_and = 9,
  anon_sym_fn = 10,
  anon_sym_extern = 11,
  anon_sym_COLON = 12,
  anon_sym_DOT_DOT_DOT = 13,
  anon_sym_DASH_GT = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_PLUS = 17,
  anon_sym_mut = 18,
  sym_public = 19,
  anon_sym_class = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym_ref = 23,
  anon_sym_uni = 24,
  sym_self = 25,
  sym_comment = 26,
  sym_constant = 27,
  sym_source_file = 28,
  sym__top_level = 29,
  sym_import = 30,
  sym_path = 31,
  sym_symbols = 32,
  sym__symbol = 33,
  sym_import_as = 34,
  sym_tags = 35,
  sym_external_function = 36,
  sym_extern_arguments = 37,
  sym_module_method = 38,
  sym_method_arguments = 39,
  sym_argument = 40,
  sym_rest_argument = 41,
  sym__returns = 42,
  sym_type_parameters = 43,
  sym_type_parameter = 44,
  sym_type_parameter_requirements = 45,
  sym__type_parameter_requirement = 46,
  sym_mutable_requirement = 47,
  sym_class = 48,
  sym_class_body = 49,
  sym__type = 50,
  sym_generic_type = 51,
  sym_type_arguments = 52,
  sym_ref_type = 53,
  sym_mut_type = 54,
  sym_uni_type = 55,
  sym_fn_type = 56,
  sym_fn_type_arguments = 57,
  sym_block = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_path_repeat1 = 60,
  aux_sym_symbols_repeat1 = 61,
  aux_sym_tags_repeat1 = 62,
  aux_sym_extern_arguments_repeat1 = 63,
  aux_sym_type_parameters_repeat1 = 64,
  aux_sym_type_parameter_requirements_repeat1 = 65,
  aux_sym_type_arguments_repeat1 = 66,
  alias_sym_type = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_import] = "import",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_as] = "as",
  [anon_sym_if] = "if",
  [anon_sym_and] = "and",
  [anon_sym_fn] = "fn",
  [anon_sym_extern] = "extern",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_mut] = "mut",
  [sym_public] = "public",
  [anon_sym_class] = "class",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_ref] = "ref",
  [anon_sym_uni] = "uni",
  [sym_self] = "self",
  [sym_comment] = "comment",
  [sym_constant] = "constant",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym_import] = "import",
  [sym_path] = "path",
  [sym_symbols] = "symbols",
  [sym__symbol] = "_symbol",
  [sym_import_as] = "import_as",
  [sym_tags] = "tags",
  [sym_external_function] = "external_function",
  [sym_extern_arguments] = "arguments",
  [sym_module_method] = "module_method",
  [sym_method_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_rest_argument] = "rest_argument",
  [sym__returns] = "_returns",
  [sym_type_parameters] = "type_parameters",
  [sym_type_parameter] = "type_parameter",
  [sym_type_parameter_requirements] = "requirements",
  [sym__type_parameter_requirement] = "_type_parameter_requirement",
  [sym_mutable_requirement] = "mut",
  [sym_class] = "class",
  [sym_class_body] = "class_body",
  [sym__type] = "_type",
  [sym_generic_type] = "generic_type",
  [sym_type_arguments] = "type_arguments",
  [sym_ref_type] = "ref_type",
  [sym_mut_type] = "mut_type",
  [sym_uni_type] = "uni_type",
  [sym_fn_type] = "fn_type",
  [sym_fn_type_arguments] = "arguments",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_symbols_repeat1] = "symbols_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_extern_arguments_repeat1] = "extern_arguments_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_type_parameter_requirements_repeat1] = "type_parameter_requirements_repeat1",
  [aux_sym_type_arguments_repeat1] = "type_arguments_repeat1",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_mut] = anon_sym_mut,
  [sym_public] = sym_public,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_uni] = anon_sym_uni,
  [sym_self] = sym_self,
  [sym_comment] = sym_comment,
  [sym_constant] = sym_constant,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym_import] = sym_import,
  [sym_path] = sym_path,
  [sym_symbols] = sym_symbols,
  [sym__symbol] = sym__symbol,
  [sym_import_as] = sym_import_as,
  [sym_tags] = sym_tags,
  [sym_external_function] = sym_external_function,
  [sym_extern_arguments] = sym_extern_arguments,
  [sym_module_method] = sym_module_method,
  [sym_method_arguments] = sym_extern_arguments,
  [sym_argument] = sym_argument,
  [sym_rest_argument] = sym_rest_argument,
  [sym__returns] = sym__returns,
  [sym_type_parameters] = sym_type_parameters,
  [sym_type_parameter] = sym_type_parameter,
  [sym_type_parameter_requirements] = sym_type_parameter_requirements,
  [sym__type_parameter_requirement] = sym__type_parameter_requirement,
  [sym_mutable_requirement] = sym_mutable_requirement,
  [sym_class] = sym_class,
  [sym_class_body] = sym_class_body,
  [sym__type] = sym__type,
  [sym_generic_type] = sym_generic_type,
  [sym_type_arguments] = sym_type_arguments,
  [sym_ref_type] = sym_ref_type,
  [sym_mut_type] = sym_mut_type,
  [sym_uni_type] = sym_uni_type,
  [sym_fn_type] = sym_fn_type,
  [sym_fn_type_arguments] = sym_extern_arguments,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_symbols_repeat1] = aux_sym_symbols_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_extern_arguments_repeat1] = aux_sym_extern_arguments_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_type_parameter_requirements_repeat1] = aux_sym_type_parameter_requirements_repeat1,
  [aux_sym_type_arguments_repeat1] = aux_sym_type_arguments_repeat1,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [sym_public] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uni] = {
    .visible = true,
    .named = false,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [sym__symbol] = {
    .visible = false,
    .named = true,
  },
  [sym_import_as] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_external_function] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_module_method] = {
    .visible = true,
    .named = true,
  },
  [sym_method_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_rest_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__returns] = {
    .visible = false,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter_requirements] = {
    .visible = true,
    .named = true,
  },
  [sym__type_parameter_requirement] = {
    .visible = false,
    .named = true,
  },
  [sym_mutable_requirement] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_class_body] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_type] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_type] = {
    .visible = true,
    .named = true,
  },
  [sym_uni_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbols_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extern_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameter_requirements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_arguments = 2,
  field_body = 3,
  field_name = 4,
  field_path = 5,
  field_requirements = 6,
  field_returns = 7,
  field_symbols = 8,
  field_tags = 9,
  field_type = 10,
  field_type_parameters = 11,
  field_visibility = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_name] = "name",
  [field_path] = "path",
  [field_requirements] = "requirements",
  [field_returns] = "returns",
  [field_symbols] = "symbols",
  [field_tags] = "tags",
  [field_type] = "type",
  [field_type_parameters] = "type_parameters",
  [field_visibility] = "visibility",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 3},
  [13] = {.index = 22, .length = 1},
  [14] = {.index = 23, .length = 3},
  [15] = {.index = 26, .length = 3},
  [16] = {.index = 29, .length = 3},
  [17] = {.index = 32, .length = 3},
  [18] = {.index = 35, .length = 3},
  [19] = {.index = 38, .length = 3},
  [20] = {.index = 41, .length = 3},
  [21] = {.index = 44, .length = 3},
  [22] = {.index = 47, .length = 3},
  [23] = {.index = 50, .length = 4},
  [24] = {.index = 54, .length = 4},
  [25] = {.index = 58, .length = 4},
  [26] = {.index = 62, .length = 1},
  [27] = {.index = 63, .length = 1},
  [28] = {.index = 64, .length = 1},
  [29] = {.index = 65, .length = 2},
  [30] = {.index = 67, .length = 2},
  [31] = {.index = 69, .length = 4},
  [32] = {.index = 73, .length = 4},
  [33] = {.index = 77, .length = 4},
  [34] = {.index = 81, .length = 3},
  [35] = {.index = 84, .length = 4},
  [36] = {.index = 88, .length = 4},
  [37] = {.index = 92, .length = 4},
  [38] = {.index = 96, .length = 4},
  [39] = {.index = 100, .length = 5},
  [40] = {.index = 105, .length = 5},
  [41] = {.index = 110, .length = 5},
  [42] = {.index = 115, .length = 2},
  [43] = {.index = 117, .length = 2},
  [44] = {.index = 119, .length = 5},
  [45] = {.index = 124, .length = 5},
  [46] = {.index = 129, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_path, 1},
    {field_symbols, 2},
  [3] =
    {field_path, 1},
    {field_tags, 2},
  [5] =
    {field_name, 2},
  [6] =
    {field_body, 2},
    {field_name, 1},
  [8] =
    {field_path, 1},
    {field_symbols, 2},
    {field_tags, 3},
  [11] =
    {field_arguments, 3},
    {field_name, 2},
  [13] =
    {field_name, 2},
    {field_returns, 3},
  [15] =
    {field_body, 3},
    {field_name, 2},
  [17] =
    {field_name, 3},
    {field_visibility, 1},
  [19] =
    {field_body, 3},
    {field_name, 2},
    {field_visibility, 1},
  [22] =
    {field_name, 0},
  [23] =
    {field_arguments, 2},
    {field_body, 3},
    {field_name, 1},
  [26] =
    {field_body, 3},
    {field_name, 1},
    {field_returns, 2},
  [29] =
    {field_body, 3},
    {field_name, 1},
    {field_type_parameters, 2},
  [32] =
    {field_arguments, 3},
    {field_name, 2},
    {field_returns, 4},
  [35] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 2},
  [38] =
    {field_body, 4},
    {field_name, 2},
    {field_returns, 3},
  [41] =
    {field_arguments, 4},
    {field_name, 3},
    {field_visibility, 1},
  [44] =
    {field_name, 3},
    {field_returns, 4},
    {field_visibility, 1},
  [47] =
    {field_body, 4},
    {field_name, 3},
    {field_visibility, 1},
  [50] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 2},
    {field_visibility, 1},
  [54] =
    {field_body, 4},
    {field_name, 2},
    {field_returns, 3},
    {field_visibility, 1},
  [58] =
    {field_body, 4},
    {field_name, 2},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [62] =
    {field_returns, 1},
  [63] =
    {field_arguments, 1},
  [64] =
    {field_type, 1},
  [65] =
    {field_arguments, 1},
    {field_name, 0},
  [67] =
    {field_name, 0},
    {field_requirements, 1},
  [69] =
    {field_arguments, 2},
    {field_body, 4},
    {field_name, 1},
    {field_returns, 3},
  [73] =
    {field_arguments, 3},
    {field_body, 4},
    {field_name, 1},
    {field_type_parameters, 2},
  [77] =
    {field_body, 4},
    {field_name, 1},
    {field_returns, 3},
    {field_type_parameters, 2},
  [81] =
    {field_alias, 1},
    {field_alias, 2},
    {field_name, 0},
  [84] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
  [88] =
    {field_arguments, 4},
    {field_name, 3},
    {field_returns, 5},
    {field_visibility, 1},
  [92] =
    {field_arguments, 4},
    {field_body, 5},
    {field_name, 3},
    {field_visibility, 1},
  [96] =
    {field_body, 5},
    {field_name, 3},
    {field_returns, 4},
    {field_visibility, 1},
  [100] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
    {field_visibility, 1},
  [105] =
    {field_arguments, 4},
    {field_body, 5},
    {field_name, 2},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [110] =
    {field_body, 5},
    {field_name, 2},
    {field_returns, 4},
    {field_type_parameters, 3},
    {field_visibility, 1},
  [115] =
    {field_name, 0},
    {field_type, 2},
  [117] =
    {field_arguments, 1},
    {field_returns, 2},
  [119] =
    {field_arguments, 3},
    {field_body, 5},
    {field_name, 1},
    {field_returns, 4},
    {field_type_parameters, 2},
  [124] =
    {field_arguments, 4},
    {field_body, 6},
    {field_name, 3},
    {field_returns, 5},
    {field_visibility, 1},
  [129] =
    {field_arguments, 4},
    {field_body, 6},
    {field_name, 2},
    {field_returns, 5},
    {field_type_parameters, 3},
    {field_visibility, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [12] = {
    [0] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(10);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '.') ADVANCE(2);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_constant);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'm') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == 'r') ADVANCE(8);
      if (lookahead == 's') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_public);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_uni);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_self);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 0},
  [185] = {.lex_state = 0},
  [186] = {.lex_state = 0},
  [187] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [sym_public] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_uni] = ACTIONS(1),
    [sym_self] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_constant] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(185),
    [sym__top_level] = STATE(16),
    [sym_import] = STATE(16),
    [sym_external_function] = STATE(16),
    [sym_module_method] = STATE(16),
    [sym_class] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_class] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    STATE(15), 1,
      sym_fn_type_arguments,
    STATE(39), 1,
      sym__returns,
    ACTIONS(13), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [26] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(139), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [56] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(142), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [86] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(122), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [116] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    STATE(122), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [146] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(122), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [176] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(122), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [206] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(122), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [233] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(34), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [260] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(32), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [287] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(31), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [314] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(41), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [341] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_mut,
    ACTIONS(25), 1,
      anon_sym_ref,
    ACTIONS(27), 1,
      anon_sym_uni,
    ACTIONS(29), 1,
      sym_constant,
    STATE(147), 6,
      sym__type,
      sym_generic_type,
      sym_ref_type,
      sym_mut_type,
      sym_uni_type,
      sym_fn_type,
  [368] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    STATE(38), 1,
      sym__returns,
    ACTIONS(41), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [388] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(18), 6,
      sym__top_level,
      sym_import,
      sym_external_function,
      sym_module_method,
      sym_class,
      aux_sym_source_file_repeat1,
  [412] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_type_arguments,
    ACTIONS(45), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [432] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_import,
    ACTIONS(54), 1,
      anon_sym_fn,
    ACTIONS(57), 1,
      anon_sym_class,
    STATE(18), 6,
      sym__top_level,
      sym_import,
      sym_external_function,
      sym_module_method,
      sym_class,
      aux_sym_source_file_repeat1,
  [456] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_extern_arguments,
    STATE(51), 1,
      sym__returns,
    STATE(86), 1,
      sym_block,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [484] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_extern_arguments,
    STATE(60), 1,
      sym__returns,
    STATE(102), 1,
      sym_block,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_class,
      anon_sym_LBRACE,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_class,
      anon_sym_LBRACE,
  [557] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_class,
      anon_sym_LBRACE,
  [572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_class,
      anon_sym_LBRACE,
  [617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_class,
      anon_sym_LBRACE,
  [647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DOT,
    STATE(30), 1,
      aux_sym_path_repeat1,
    ACTIONS(86), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [693] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DOT,
    STATE(30), 1,
      aux_sym_path_repeat1,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [725] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_if,
    STATE(49), 1,
      sym_symbols,
    STATE(80), 1,
      sym_tags,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [747] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym__returns,
    STATE(108), 1,
      sym_block,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [769] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DOT,
    STATE(33), 1,
      aux_sym_path_repeat1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [787] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [815] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym__returns,
    STATE(84), 1,
      sym_block,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_fn,
      anon_sym_RBRACK,
      anon_sym_class,
      anon_sym_LBRACE,
  [851] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    STATE(63), 1,
      sym_type_parameters,
    STATE(82), 1,
      sym_method_arguments,
    STATE(83), 1,
      sym_block,
    STATE(162), 1,
      sym__returns,
  [879] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    STATE(48), 1,
      sym_type_parameters,
    STATE(76), 1,
      sym_method_arguments,
    STATE(113), 1,
      sym_block,
    STATE(169), 1,
      sym__returns,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [920] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_mut,
    ACTIONS(127), 1,
      sym_constant,
    ACTIONS(123), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(95), 3,
      sym__type_parameter_requirement,
      sym_mutable_requirement,
      sym_generic_type,
  [939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [951] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_and,
    STATE(54), 1,
      aux_sym_tags_repeat1,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [967] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      sym_method_arguments,
    STATE(92), 1,
      sym_block,
    STATE(157), 1,
      sym__returns,
  [989] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_if,
    STATE(96), 1,
      sym_tags,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1005] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_and,
    STATE(50), 1,
      aux_sym_tags_repeat1,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1021] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(107), 1,
      sym_block,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1037] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    ACTIONS(148), 1,
      sym_constant,
    ACTIONS(144), 2,
      sym_self,
      sym_identifier,
    STATE(164), 2,
      sym__symbol,
      sym_import_as,
  [1055] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_constant,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      sym_self,
      sym_identifier,
    STATE(144), 2,
      sym__symbol,
      sym_import_as,
  [1073] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_and,
    STATE(50), 1,
      aux_sym_tags_repeat1,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1089] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(110), 1,
      sym_block,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [1129] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(91), 1,
      sym_block,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1145] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_constant,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      sym_self,
      sym_identifier,
    STATE(164), 2,
      sym__symbol,
      sym_import_as,
  [1163] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_block,
    ACTIONS(164), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [1203] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    STATE(97), 1,
      sym_block,
    STATE(99), 1,
      sym_method_arguments,
    STATE(149), 1,
      sym__returns,
  [1225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_DASH_GT,
      anon_sym_class,
      anon_sym_LBRACE,
  [1237] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_constant,
    ACTIONS(144), 2,
      sym_self,
      sym_identifier,
    STATE(164), 2,
      sym__symbol,
      sym_import_as,
  [1252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [1263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(161), 1,
      sym_argument,
    STATE(172), 1,
      sym_rest_argument,
  [1282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [1293] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_mut,
    ACTIONS(127), 1,
      sym_constant,
    STATE(120), 3,
      sym__type_parameter_requirement,
      sym_mutable_requirement,
      sym_generic_type,
  [1308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_type_arguments,
    ACTIONS(182), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [1323] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(155), 1,
      sym_rest_argument,
    STATE(161), 1,
      sym_argument,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [1353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_if,
      anon_sym_fn,
      anon_sym_class,
  [1364] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(194), 3,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_and,
      anon_sym_fn,
      anon_sym_class,
  [1390] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_block,
    STATE(158), 1,
      sym__returns,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_PLUS,
    STATE(78), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(198), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_type_arguments_repeat1,
    ACTIONS(206), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_PLUS,
    STATE(78), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1468] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(101), 1,
      sym_block,
    STATE(168), 1,
      sym__returns,
  [1484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1554] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(105), 1,
      sym_block,
    STATE(167), 1,
      sym__returns,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_PLUS,
    STATE(81), 1,
      aux_sym_type_parameter_requirements_repeat1,
    ACTIONS(236), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1644] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(134), 1,
      sym_argument,
  [1660] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(111), 1,
      sym_block,
    STATE(171), 1,
      sym__returns,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_fn,
      anon_sym_class,
  [1816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_COLON,
    STATE(166), 1,
      sym_type_parameter_requirements,
    ACTIONS(274), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1830] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_as,
    ACTIONS(278), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1850] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      aux_sym_symbols_repeat1,
  [1863] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(145), 1,
      aux_sym_extern_arguments_repeat1,
  [1876] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      sym_identifier,
    ACTIONS(295), 1,
      anon_sym_extern,
    ACTIONS(297), 1,
      sym_public,
  [1889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [1898] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    STATE(117), 1,
      aux_sym_symbols_repeat1,
  [1911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1920] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(118), 1,
      sym_argument,
  [1933] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    STATE(137), 1,
      aux_sym_extern_arguments_repeat1,
  [1946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_RBRACK,
    ACTIONS(309), 1,
      sym_constant,
    STATE(132), 1,
      sym_type_parameter,
  [1968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_COMMA,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
    STATE(140), 1,
      aux_sym_type_parameters_repeat1,
  [1981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1990] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_constant,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
    STATE(151), 1,
      sym_type_parameter,
  [2003] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(317), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_type_arguments_repeat1,
  [2016] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(160), 1,
      sym_rest_argument,
  [2029] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RBRACK,
    STATE(127), 1,
      aux_sym_type_parameters_repeat1,
  [2042] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_type_arguments_repeat1,
  [2055] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    ACTIONS(327), 1,
      anon_sym_COMMA,
    STATE(124), 1,
      aux_sym_extern_arguments_repeat1,
  [2068] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    STATE(161), 1,
      sym_argument,
  [2081] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
    STATE(161), 1,
      sym_argument,
  [2094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    STATE(137), 1,
      aux_sym_extern_arguments_repeat1,
  [2107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_constant,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(151), 1,
      sym_type_parameter,
  [2120] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_RPAREN,
    STATE(133), 1,
      aux_sym_type_arguments_repeat1,
  [2133] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
    STATE(140), 1,
      aux_sym_type_parameters_repeat1,
  [2146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_as,
    ACTIONS(278), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2157] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    ACTIONS(353), 1,
      anon_sym_RBRACK,
    STATE(130), 1,
      aux_sym_type_arguments_repeat1,
  [2170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
  [2179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COMMA,
    ACTIONS(359), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      aux_sym_symbols_repeat1,
  [2192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    ACTIONS(361), 1,
      anon_sym_COMMA,
    STATE(137), 1,
      aux_sym_extern_arguments_repeat1,
  [2205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 3,
      anon_sym_LPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(161), 1,
      sym_argument,
  [2232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(112), 1,
      sym_block,
  [2242] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym_identifier,
    STATE(35), 1,
      sym_path,
  [2252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2276] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      sym_identifier,
    ACTIONS(375), 1,
      anon_sym_extern,
  [2286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(377), 1,
      anon_sym_COMMA,
  [2296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_block,
  [2314] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(106), 1,
      sym_block,
  [2324] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2332] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(383), 1,
      anon_sym_COMMA,
  [2342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2350] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(100), 1,
      sym_block,
  [2360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2376] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_LBRACE,
    STATE(93), 1,
      sym_class_body,
  [2386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_block,
  [2404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(109), 1,
      sym_block,
  [2414] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(89), 1,
      sym_block,
  [2424] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_constant,
    STATE(151), 1,
      sym_type_parameter,
  [2434] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(94), 1,
      sym_block,
  [2444] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_COMMA,
    ACTIONS(393), 1,
      anon_sym_RPAREN,
  [2454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      sym_identifier,
  [2469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_RPAREN,
  [2476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      sym_identifier,
  [2483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_constant,
  [2490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      sym_identifier,
  [2497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
  [2504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_RBRACE,
  [2511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_identifier,
  [2518] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_RBRACE,
  [2525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_RPAREN,
  [2532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      sym_identifier,
  [2539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      ts_builtin_sym_end,
  [2546] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      sym_constant,
  [2553] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 206,
  [SMALL_STATE(10)] = 233,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 314,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 368,
  [SMALL_STATE(16)] = 388,
  [SMALL_STATE(17)] = 412,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 484,
  [SMALL_STATE(21)] = 512,
  [SMALL_STATE(22)] = 527,
  [SMALL_STATE(23)] = 542,
  [SMALL_STATE(24)] = 557,
  [SMALL_STATE(25)] = 572,
  [SMALL_STATE(26)] = 587,
  [SMALL_STATE(27)] = 602,
  [SMALL_STATE(28)] = 617,
  [SMALL_STATE(29)] = 632,
  [SMALL_STATE(30)] = 647,
  [SMALL_STATE(31)] = 665,
  [SMALL_STATE(32)] = 679,
  [SMALL_STATE(33)] = 693,
  [SMALL_STATE(34)] = 711,
  [SMALL_STATE(35)] = 725,
  [SMALL_STATE(36)] = 747,
  [SMALL_STATE(37)] = 769,
  [SMALL_STATE(38)] = 787,
  [SMALL_STATE(39)] = 801,
  [SMALL_STATE(40)] = 815,
  [SMALL_STATE(41)] = 837,
  [SMALL_STATE(42)] = 851,
  [SMALL_STATE(43)] = 879,
  [SMALL_STATE(44)] = 907,
  [SMALL_STATE(45)] = 920,
  [SMALL_STATE(46)] = 939,
  [SMALL_STATE(47)] = 951,
  [SMALL_STATE(48)] = 967,
  [SMALL_STATE(49)] = 989,
  [SMALL_STATE(50)] = 1005,
  [SMALL_STATE(51)] = 1021,
  [SMALL_STATE(52)] = 1037,
  [SMALL_STATE(53)] = 1055,
  [SMALL_STATE(54)] = 1073,
  [SMALL_STATE(55)] = 1089,
  [SMALL_STATE(56)] = 1105,
  [SMALL_STATE(57)] = 1117,
  [SMALL_STATE(58)] = 1129,
  [SMALL_STATE(59)] = 1145,
  [SMALL_STATE(60)] = 1163,
  [SMALL_STATE(61)] = 1179,
  [SMALL_STATE(62)] = 1191,
  [SMALL_STATE(63)] = 1203,
  [SMALL_STATE(64)] = 1225,
  [SMALL_STATE(65)] = 1237,
  [SMALL_STATE(66)] = 1252,
  [SMALL_STATE(67)] = 1263,
  [SMALL_STATE(68)] = 1282,
  [SMALL_STATE(69)] = 1293,
  [SMALL_STATE(70)] = 1308,
  [SMALL_STATE(71)] = 1323,
  [SMALL_STATE(72)] = 1342,
  [SMALL_STATE(73)] = 1353,
  [SMALL_STATE(74)] = 1364,
  [SMALL_STATE(75)] = 1379,
  [SMALL_STATE(76)] = 1390,
  [SMALL_STATE(77)] = 1406,
  [SMALL_STATE(78)] = 1416,
  [SMALL_STATE(79)] = 1430,
  [SMALL_STATE(80)] = 1444,
  [SMALL_STATE(81)] = 1454,
  [SMALL_STATE(82)] = 1468,
  [SMALL_STATE(83)] = 1484,
  [SMALL_STATE(84)] = 1494,
  [SMALL_STATE(85)] = 1504,
  [SMALL_STATE(86)] = 1514,
  [SMALL_STATE(87)] = 1524,
  [SMALL_STATE(88)] = 1534,
  [SMALL_STATE(89)] = 1544,
  [SMALL_STATE(90)] = 1554,
  [SMALL_STATE(91)] = 1570,
  [SMALL_STATE(92)] = 1580,
  [SMALL_STATE(93)] = 1590,
  [SMALL_STATE(94)] = 1600,
  [SMALL_STATE(95)] = 1610,
  [SMALL_STATE(96)] = 1624,
  [SMALL_STATE(97)] = 1634,
  [SMALL_STATE(98)] = 1644,
  [SMALL_STATE(99)] = 1660,
  [SMALL_STATE(100)] = 1676,
  [SMALL_STATE(101)] = 1686,
  [SMALL_STATE(102)] = 1696,
  [SMALL_STATE(103)] = 1706,
  [SMALL_STATE(104)] = 1716,
  [SMALL_STATE(105)] = 1726,
  [SMALL_STATE(106)] = 1736,
  [SMALL_STATE(107)] = 1746,
  [SMALL_STATE(108)] = 1756,
  [SMALL_STATE(109)] = 1766,
  [SMALL_STATE(110)] = 1776,
  [SMALL_STATE(111)] = 1786,
  [SMALL_STATE(112)] = 1796,
  [SMALL_STATE(113)] = 1806,
  [SMALL_STATE(114)] = 1816,
  [SMALL_STATE(115)] = 1830,
  [SMALL_STATE(116)] = 1841,
  [SMALL_STATE(117)] = 1850,
  [SMALL_STATE(118)] = 1863,
  [SMALL_STATE(119)] = 1876,
  [SMALL_STATE(120)] = 1889,
  [SMALL_STATE(121)] = 1898,
  [SMALL_STATE(122)] = 1911,
  [SMALL_STATE(123)] = 1920,
  [SMALL_STATE(124)] = 1933,
  [SMALL_STATE(125)] = 1946,
  [SMALL_STATE(126)] = 1955,
  [SMALL_STATE(127)] = 1968,
  [SMALL_STATE(128)] = 1981,
  [SMALL_STATE(129)] = 1990,
  [SMALL_STATE(130)] = 2003,
  [SMALL_STATE(131)] = 2016,
  [SMALL_STATE(132)] = 2029,
  [SMALL_STATE(133)] = 2042,
  [SMALL_STATE(134)] = 2055,
  [SMALL_STATE(135)] = 2068,
  [SMALL_STATE(136)] = 2081,
  [SMALL_STATE(137)] = 2094,
  [SMALL_STATE(138)] = 2107,
  [SMALL_STATE(139)] = 2120,
  [SMALL_STATE(140)] = 2133,
  [SMALL_STATE(141)] = 2146,
  [SMALL_STATE(142)] = 2157,
  [SMALL_STATE(143)] = 2170,
  [SMALL_STATE(144)] = 2179,
  [SMALL_STATE(145)] = 2192,
  [SMALL_STATE(146)] = 2205,
  [SMALL_STATE(147)] = 2214,
  [SMALL_STATE(148)] = 2222,
  [SMALL_STATE(149)] = 2232,
  [SMALL_STATE(150)] = 2242,
  [SMALL_STATE(151)] = 2252,
  [SMALL_STATE(152)] = 2260,
  [SMALL_STATE(153)] = 2268,
  [SMALL_STATE(154)] = 2276,
  [SMALL_STATE(155)] = 2286,
  [SMALL_STATE(156)] = 2296,
  [SMALL_STATE(157)] = 2304,
  [SMALL_STATE(158)] = 2314,
  [SMALL_STATE(159)] = 2324,
  [SMALL_STATE(160)] = 2332,
  [SMALL_STATE(161)] = 2342,
  [SMALL_STATE(162)] = 2350,
  [SMALL_STATE(163)] = 2360,
  [SMALL_STATE(164)] = 2368,
  [SMALL_STATE(165)] = 2376,
  [SMALL_STATE(166)] = 2386,
  [SMALL_STATE(167)] = 2394,
  [SMALL_STATE(168)] = 2404,
  [SMALL_STATE(169)] = 2414,
  [SMALL_STATE(170)] = 2424,
  [SMALL_STATE(171)] = 2434,
  [SMALL_STATE(172)] = 2444,
  [SMALL_STATE(173)] = 2454,
  [SMALL_STATE(174)] = 2462,
  [SMALL_STATE(175)] = 2469,
  [SMALL_STATE(176)] = 2476,
  [SMALL_STATE(177)] = 2483,
  [SMALL_STATE(178)] = 2490,
  [SMALL_STATE(179)] = 2497,
  [SMALL_STATE(180)] = 2504,
  [SMALL_STATE(181)] = 2511,
  [SMALL_STATE(182)] = 2518,
  [SMALL_STATE(183)] = 2525,
  [SMALL_STATE(184)] = 2532,
  [SMALL_STATE(185)] = 2539,
  [SMALL_STATE(186)] = 2546,
  [SMALL_STATE(187)] = 2553,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(186),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 2, .production_id = 27),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, .production_id = 12),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(150),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(119),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(186),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 10),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 3, .production_id = 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 4),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, .production_id = 29),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type_arguments, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2), SHIFT_REPEAT(178),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_type, 2, .production_id = 28),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_type, 2, .production_id = 28),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uni_type, 2, .production_id = 28),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, .production_id = 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 20),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 3, .production_id = 43),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 2, .production_id = 26),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 7),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__returns, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3, .production_id = 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2), SHIFT_REPEAT(174),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 21),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 17),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 7),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 6),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 36),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 8),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_arguments, 4),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(187),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 5),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_parameter_requirement, 1, .production_id = 12),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 4),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 7, .production_id = 46),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameter_requirements_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameter_requirements_repeat1, 2), SHIFT_REPEAT(69),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2), SHIFT_REPEAT(9),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3, .production_id = 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 3, .production_id = 5),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 18),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 19),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 5, .production_id = 22),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_body, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 23),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 24),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 7, .production_id = 45),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 25),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 3, .production_id = 5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 44),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter_requirements, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 6),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 16),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 15),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 14),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 4, .production_id = 9),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 41),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 40),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 6, .production_id = 39),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 38),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 37),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 31),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function, 6, .production_id = 35),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 32),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 5, .production_id = 33),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_method, 4, .production_id = 11),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 1, .production_id = 13),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol, 1),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 2),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_symbols_repeat1, 2), SHIFT_REPEAT(65),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_symbols_repeat1, 2),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(184),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(154),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 5),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extern_arguments_repeat1, 2), SHIFT_REPEAT(148),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extern_arguments_repeat1, 2),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [344] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2), SHIFT_REPEAT(170),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mutable_requirement, 1),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 42),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 3),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 2),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(176),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest_argument, 1),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 5),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_arguments, 4),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 2, .production_id = 30),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(183),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_as, 3, .production_id = 34),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [413] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_inko() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
